apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80


#Слагане на имидж версия
kubectl set image deployment.v1.apps/nginx-deployment nginx=nginx:1.16.1
#Смяна на имидж версия от командния ред
kubectl set image deployment/nginx-deployment nginx=nginx:1.16.1
#Редактиране на деплоймънт
kubectl edit deployment/nginx-deployment
#Статус на деплоймънт
kubectl rollout status deployment/nginx-deployment


#Провека за историята на деплоймънтите
kubectl rollout history deployment/nginx-deployment

kubectl rollout history deployment/nginx-deployment --revision=2

#Връщане на предишният деплоймънт
kubectl rollout undo deployment/nginx-deployment
#Връщане към определена версия
kubectl rollout undo deployment/nginx-deployment --to-revision=2


kubectl autoscale deployment/nginx-deployment --min=10 --max=15 --cpu-percent=80


kubectl rollout pause deployment/nginx-deployment

#Добавете към deployment-a стратегия:
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 5
     maxUnavailable: 2
