apiVersion: v1
kind: Service
metadata:
  name: nginx-service-node-port
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007    
